# Generated by Django 5.1.3 on 2025-02-09 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_userquestionstatus_question_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionStatus',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
