# Generated by Django 5.1.3 on 2025-02-09 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_pdfrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDFRecord',
        ),
    ]
