# Generated by Django 5.1.3 on 2025-02-09 13:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_codesubmission_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
