# Generated by Django 5.1.3 on 2025-02-09 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_codesubmission_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesubmission',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='codesubmission',
            name='created_at',
        ),
    ]
