# Generated by Django 5.1.3 on 2025-02-10 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
